[toolchain]

[features]
resolution = true
skip-lint = false
idl-build = true  # Add this line

[programs.localnet]
second_swap = "9qxgVVgdrRCTP6BvYrDePWhk9FV5gxzggp79HDo4xkwo"

[programs.devnet]
second_swap = "4K6S71TbX3wTaxSpETDHq8mK3yZrJJPYq5nxVKKbXuPj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build --idl-skip-lint" # Add this line
